Make non-global RegExps global so they can "replace all" occurrences
tc39/proposal-string-replaceall pull request #20
Opened 2019-07-09 10:56 UTC by mathiasbynens

This is one of the potential solutions to #16.

2019-07-18 16:06 UTC, ExE-Boss approved these changes
I am in favour of this.

2019-09-18 14:51 UTC, mathiasbynens commented
Alternative approach: #24

2019-09-18 15:51 UTC, ljharb requested changes

2019-09-18 15:51 UTC, ljharb commented on spec.html
> +    1. Let _flags_ be ? ToString(? Get(_rx_, `"flags"`)).
if flags is undefined, this should be the empty string, not the string undefined, to match the RegExp constructor.

2019-09-23 06:58 UTC, mathiasbynens commented
We're going with #24 instead.

2019-09-23 06:58 UTC, closed without merging